/**
 * Maps country codes to catalog regions for subscription display.
 * Countries without dedicated catalog data fall back to a region with similar pricing.
 * Catalog regions with seed data: MA, US, FR, GB, CA, DE, AE, EG
 */

export const CATALOG_REGIONS = ["MA", "US", "FR", "GB", "CA", "DE", "AE", "EG"] as const;
export type CatalogRegion = (typeof CATALOG_REGIONS)[number];

/** Human-readable region names for UI */
export const REGION_NAMES: Record<CatalogRegion, string> = {
  MA: "Morocco",
  US: "United States",
  FR: "France",
  GB: "United Kingdom",
  CA: "Canada",
  DE: "Germany",
  AE: "UAE",
  EG: "Egypt",
};

/**
 * Maps a user's country_code to the catalog region whose subscriptions to show.
 * Countries with dedicated catalog return themselves; others fall back to a region
 * with similar pricing (e.g. Nigeria, Ghana → US; Tunisia, Algeria → MA).
 */
const COUNTRY_TO_REGION: Record<string, CatalogRegion> = {
  // Countries with dedicated catalog — return self
  MA: "MA",
  US: "US",
  FR: "FR",
  GB: "GB",
  CA: "CA",
  DE: "DE",
  AE: "AE",
  EG: "EG",

  // North Africa / MENA (Morocco pricing) — MA
  DZ: "MA",
  TN: "MA",
  LY: "MA",
  MR: "MA",

  // Gulf — AE
  SA: "AE",
  BH: "AE",
  KW: "AE",
  OM: "AE",
  QA: "AE",
  YE: "AE",
  JO: "AE",
  LB: "AE",
  SY: "AE",
  IQ: "AE",
  IR: "AE",
  PS: "AE",

  // Francophone Africa / Europe — FR
  SN: "FR",
  CI: "FR",
  CM: "FR",
  NE: "FR",
  TG: "FR",
  BJ: "FR",
  BF: "FR",
  ML: "FR",
  GA: "FR",
  CG: "FR",
  CD: "FR",
  MG: "FR",
  RE: "FR",
  YT: "FR",
  MC: "FR",
  LU: "FR",
  BE: "FR",
  CH: "FR",
  AD: "FR",
  SM: "FR",
  VA: "FR",

  // US dollar pricing (Africa, Americas, Asia, Oceania without dedicated catalog)
  NG: "US",
  GH: "US",
  KE: "US",
  ZA: "US",
  ZW: "US",
  ZM: "US",
  TZ: "US",
  UG: "US",
  RW: "US",
  MW: "US",
  SZ: "US",
  LS: "US",
  BW: "US",
  NA: "US",
  ET: "US",
  SD: "US",
  SS: "US",
  SO: "US",
  AO: "US",
  MZ: "US",
  MG: "US",
  GM: "US",
  GN: "US",
  GW: "US",
  LR: "US",
  SL: "US",
  CV: "US",
  GQ: "US",
  ST: "US",
  MU: "US",
  SC: "US",
  KM: "US",
  ER: "US",
  DJ: "US",
  CF: "US",
  TD: "US",
  BI: "US",
  AR: "US",
  BR: "US",
  CL: "US",
  CO: "US",
  PE: "US",
  MX: "US",
  EC: "US",
  VE: "US",
  UY: "US",
  PY: "US",
  BO: "US",
  CR: "US",
  PA: "US",
  HN: "US",
  SV: "US",
  GT: "US",
  NI: "US",
  DO: "US",
  CU: "US",
  HT: "US",
  BZ: "US",
  GY: "US",
  SR: "US",
  AG: "US",
  GD: "US",
  DM: "US",
  LC: "US",
  VC: "US",
  KN: "US",
  AF: "US",
  IN: "US",
  PK: "US",
  BD: "US",
  ID: "US",
  PH: "US",
  VN: "US",
  TH: "US",
  MY: "US",
  SG: "US",
  KH: "US",
  LA: "US",
  MM: "US",
  NP: "US",
  LK: "US",
  TW: "US",
  JP: "US",
  KR: "US",
  CN: "US",
  RU: "US",
  KZ: "US",
  UZ: "US",
  TJ: "US",
  TM: "US",
  KG: "US",
  MN: "US",
  AU: "US",
  NZ: "US",
  FJ: "US",
  PG: "US",
  SB: "US",
  VU: "US",
  NR: "US",
  FM: "US",
  MH: "US",
  PW: "US",
  KI: "US",
  TV: "US",
  TO: "US",
  WS: "US",
  HK: "US",
  MO: "US",
  TR: "US",
  IL: "US",
  BT: "US",
  MV: "US",
  BN: "US",
  QA: "AE",
  OM: "AE",

  // UK / Ireland / Malta / Cyprus — GB
  IE: "GB",
  JM: "GB",
  TT: "GB",
  BS: "GB",
  BB: "GB",
  MT: "GB",
  CY: "GB",

  // Eurozone / Central Europe — DE
  AT: "DE",
  NL: "DE",
  ES: "DE",
  IT: "DE",
  PT: "DE",
  GR: "DE",
  FI: "DE",
  SE: "DE",
  DK: "DE",
  NO: "DE",
  PL: "DE",
  CZ: "DE",
  SK: "DE",
  HU: "DE",
  RO: "DE",
  BG: "DE",
  HR: "DE",
  SI: "DE",
  EE: "DE",
  LV: "DE",
  LT: "DE",
  AL: "DE",
  MK: "DE",
  RS: "DE",
  BA: "DE",
  ME: "DE",
  XK: "DE",
  BY: "DE",
  UA: "DE",
  MD: "DE",
  GE: "DE",
  AM: "DE",
  AZ: "DE",
  LI: "DE",
  IS: "DE",
};

const DEFAULT_REGION: CatalogRegion = "US";

/**
 * Get the catalog region for a given country code.
 * Returns the region whose subscription catalog to display.
 */
export function getCatalogRegion(countryCode: string | null | undefined): CatalogRegion | null {
  if (!countryCode || typeof countryCode !== "string") return null;
  const normalized = countryCode.toUpperCase().trim();
  if (!normalized) return null;
  return (COUNTRY_TO_REGION[normalized] as CatalogRegion) ?? DEFAULT_REGION;
}
